# Generated by Django 4.1.7 on 2023-03-27 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Notification template ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, max_length=1000, verbose_name='message')),
                ('details', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('kyc_aml', 'KYC/AML'), ('accreditation', 'Accreditation'), ('email_verification', 'Email Verification'), ('invest', 'Invest'), ('maturity', 'Maturity'), ('principal_payment', 'Principal Payment'), ('payout', 'Payout'), ('reward', 'Reward'), ('default', 'Default')], default='default', help_text='Identifies the entity associated with the notification. service identity', max_length=255, verbose_name='source_type')),
                ('source_type', models.CharField(blank=True, help_text='The description for the source. i.e. Maturity follow up Auto-renew ON ', max_length=1000, verbose_name='source_type')),
                ('status', models.BooleanField(default=False, help_text='True or False', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['source'], name='fcm_app_not_source_04cd9a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['source_type'], name='fcm_app_not_source__215251_idx'),
        ),
    ]
