# Generated by Django 4.1.7 on 2023-03-27 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0002_notificationtemplate_and_more'),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=200, verbose_name='UUID')),
                ('type', models.CharField(blank=True, choices=[('general', 'General'), ('note_placed', 'Note Placed'), ('note_maturity', 'Note Maturity'), ('note_rollover', 'Note Rollover'), ('accreditation_passed', 'Accreditation Passed'), ('accreditation_failed', 'Accreditation Failed'), ('verified_failed', 'Verification Failed'), ('verified_account', 'Verification Passed'), ('email_verified', 'Email Verified'), ('new_rewards', 'New Rewards'), ('welcoming_rewards', 'Welcoming Rewards'), ('forgot_password_request', 'Forgot Password Request'), ('password_changed', 'Password Changed'), ('payout_initiated', 'Payout Initiated'), ('30_days_to_maturity_auto_renew_update', '30 Days to Maturity Auto Renew Update'), ('maturity_auto_renew_update', 'Maturity Auto Renew Update')], default='general', help_text='The type the of notification', max_length=1000, verbose_name='Type')),
                ('details', models.JSONField(blank=True, null=True)),
                ('fcm_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('read', 'Read'), ('pending', 'Pending'), ('unread', 'Unread')], default='pending', max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='fcm_app.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
            },
        ),
    ]
