# Generated by Django 4.1.7 on 2023-03-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emailnotification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['status'], name='emails_emai_status_2ad1df_idx'),
        ),
    ]
